{% set name = "pixi-pack" %}
{% set version = "0.1.8" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://github.com/quantco/{{ name }}/archive/refs/tags/v{{ version }}.tar.gz
  sha256: c7b45bdbed76e37405e68968816c044ce99af787b59eafd6b846bdc5938da801
build:
  number: 0

requirements:
  build:
    - {{ compiler('rust') }}
    - {{ compiler('c') }}
    - {{ stdlib('c') }}
    - cargo-bundle-licenses
    - pkg-config
    - binutils  # [win]
  host:
    - openssl  # [unix]

test:
  commands:
    - pixi-pack --help

about:
  home: https://github.com/quantco/pixi-pack
  summary: 📦 A tool to pack and unpack conda environments created with pixi
  license: BSD-3-Clause
  license_file:
    - LICENSE
    - THIRDPARTY.yml

extra:
  recipe-maintainers:
    - pavelzw
